// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP0V3jAWH0urRmwXW86vt0RUVp65NPeQE',
    appId: '1:293183117815:web:a5989c04bb97c45221f6f2',
    messagingSenderId: '293183117815',
    projectId: 'flutterprojectnote',
    authDomain: 'flutterprojectnote.firebaseapp.com',
    storageBucket: 'flutterprojectnote.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcedap0d9ujdxeUQfm4pj82jhyZK5btBk',
    appId: '1:293183117815:android:188d9ccbbae2f9c421f6f2',
    messagingSenderId: '293183117815',
    projectId: 'flutterprojectnote',
    storageBucket: 'flutterprojectnote.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDik0wkEnTazZbYz3ydKpAKQu6nLCHSEM',
    appId: '1:293183117815:ios:b3d041623476af7c21f6f2',
    messagingSenderId: '293183117815',
    projectId: 'flutterprojectnote',
    storageBucket: 'flutterprojectnote.appspot.com',
    iosClientId: '293183117815-pqhjjvvvfkn8aaeigettu5k3k3ntefoe.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseProjectnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDik0wkEnTazZbYz3ydKpAKQu6nLCHSEM',
    appId: '1:293183117815:ios:b3d041623476af7c21f6f2',
    messagingSenderId: '293183117815',
    projectId: 'flutterprojectnote',
    storageBucket: 'flutterprojectnote.appspot.com',
    iosClientId: '293183117815-pqhjjvvvfkn8aaeigettu5k3k3ntefoe.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseProjectnote',
  );
}
